add meetup109 report
kanazawarb/meetup pull request #1243
Opened 2021-09-22 13:48 UTC by cottondesu

meetup109のレポートページを作成しました。
確認のほどよろしくお願いします。

2021-09-22 16:18 UTC, muryoimpl requested changes

2021-09-22 16:18 UTC, muryoimpl commented on 109/report.md
> +* [Kanazawa.rb meetup 109 - 30days](https://30d.jp/kzrb/98)
30daysのリンクが前回のものみたいです。99が正しそう

2021-09-23 05:33 UTC, cottondesu commented on 109/report.md
> +* [Kanazawa.rb meetup 109 - 30days](https://30d.jp/kzrb/98)
@muryoimpl さん
確認漏れでした。
URLを修正してプッシュしました。
確認お願いします。

2021-09-23 08:32 UTC, muryoimpl approved these changes
よさそうです

2021-09-23 11:45 UTC, merged